apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesStrategicMerge:
- replica-and-rollout-strategy.yaml

images:
- name: patrah/myjsapp
  newName: patrah/myjsapp
  newTag: v1.0.1
